### PR TITLE
Change constructor accessibility in order to allow mocking

### PR DESCRIPTION
**Pull request by Cussa**
Allows mocking the BatchGet and BatchWrite classes (in a way)

## Description
Today we are not able to mock the BatchGet and BatchWrite classes. A possible workaround is to create fake classes that inherits from these classes and mock the returns. However, as these classes have a `internal` only constructor, this is not possible. Having them as `protected internal` would allow us to have this behaviour.

## Motivation and Context
We want to use Moq in order to Unit test our code.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [X] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [X] I have read the **README** document
- [ ] I have added tests to cover my changes
- [X] All new and existing tests passed

## License
- [X] I confirm that this pull request can be released under the Apache 2 license

[issues]: https://github.com/aws/aws-sdk-net/issues
[license]: http://aws.amazon.com/apache2.0/
[cla]: http://en.wikipedia.org/wiki/Contributor_License_Agreement

### CODE REVIEW

**Review by peterrsongg — DISMISSED** [review]
The change itself looks good, but we still need to run it through a full dry run. I'd also like to discuss with others on the team if there could be any repercussions to making it protected internal. Approving for now

**Comment by peterrsongg** [comment]
Dismissing my approval because in[ this commit ](https://github.com/aws/aws-sdk-net/commit/c2f870f107fdcee9b90b06b401838c9f4393078f) the way we made `AsyncSearch` mockable is by creating a parameterless `protected` constructor, then marking the methods as virtual so you can provide custom implementations of those methods for mocking. Will need further discussion on which implementation we want to go with this time.

**Comment by Cussa** [comment]
That would be another possible solution for sure. We use that to make the AsyncSearch already. I just tried to make the minimum amount of changes possible. I am happy with any solution that allow us to mock it and be able to test our implementation. Thanks for keep this in consideration!

**Comment by normj** [comment]
Hi @Cussa, thanks for the PR. I would like to have a consistent experience for mocking these awkward objects and use the same approach mentioned in the commit @peterrsongg called out. If we follow that approach I see no problem pushing the PR through.

**Pull request closed without merging**
