### PR TITLE
Don't allocate memory in UnmarshallerContext.TestExpression

### PR DESCRIPTION
**Pull request by bcuff**
## Description
Improves performance and memory consumption of UnmarshallerContext.TestExpression(...)

## Motivation and Context
Performance profiling shows this as a hotspot in our dynamodb-heavy application.

## Testing
I ran the DynamoDB Integration tests.

## Screenshots (if appropriate)
image

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [x] I have read the **README** document
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed

## License

- [x] I confirm that this pull request can be released under the Apache 2 license

[issues]: https://github.com/aws/aws-sdk-net/issues
[license]: http://aws.amazon.com/apache2.0/
[cla]: http://en.wikipedia.org/wiki/Contributor_License_Agreement

### CODE REVIEW

**Comment by sstevenkang** [comment]
The change seems reasonable to me.  How much difference in performance do you see?

**Comment by bcuff** [comment]
@sstevenkang I haven't tried it yet.

**Comment by bcuff** [comment]
The flame graph above shows a fuzzy 10-20% of un-marshalling time spent in this function.

**Comment by normj** [comment]
Nice performance tweak. Thanks for the pull request and it was released in version 3.3.17.7 of AWSSDK.Core.

**Comment by bcuff** [comment]
Thanks!

**Pull request merged**
