### PR TITLE
Refactoring PersistenceManager

### PR DESCRIPTION
**Pull request by StanleyGoldman**
## Motivation and Context

https://github.com/aws/aws-sdk-net/issues/740

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have read the **README** document
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

## License

- [x] I confirm that this pull request can be released under the Apache 2 license

[issues]: https://github.com/aws/aws-sdk-net/issues
[license]: http://aws.amazon.com/apache2.0/
[cla]: http://en.wikipedia.org/wiki/Contributor_License_Agreement

### CODE REVIEW

**Comment by StanleyGoldman** [comment]
That makes sense. I moved the initialization back to the constructor with a try, catch and log.

While making that change, I figured it would be best to funnel users towards success. If an exception is caught we should initialize the `InMemoryPersistenceManager` in its place.

Let me know if you approve of the changes.

**Comment by StanleyGoldman** [comment]
I was unsure of how to log in this context. Also since I'm falling back the log should probably be a warning or info message, but I wanted to capture the exception. I'm probably overthinking things at this point...

**Comment by StanleyGoldman** [comment]
Hey @normj 

I'm going on paternity leave, but my team is still interested in getting this pull request merged. My coworker @phanatic has access to my fork and will take over for me in getting this pull request merged.

**Comment by normj** [comment]
@StanleyGoldman The PR looks good. I have pulled it into our internal build system to run the full suite of tests. I had to make a couple changes to some unit tests and switch the catch all exception to catch `UnauthorizedAccessException` so if there was any other issue we wouldn't surprise the user by switching to the in memory version. I'm getting approvals from other team members and then I will get this out soon.

Congrats on the paternity leave!

**Comment by Phanatic** [comment]
Thanks @normj ! Happy to make any further changes needed to land this.

**Comment by normj** [comment]
PR is released as part of version 3.3.106.20 of AWSSDK.Core

**Pull request merged**
