### PR TITLE
Added support for DisablePayloadSigning for DirectoryUpload

### PR DESCRIPTION
**Pull request by M4urici0GM**
## Description
Adds `DisablePayloadSigning` to `TransferUtilityUploadDirectoryRequest`

## Motivation and Context
Some providers do not implement `STREAMING-AWS4-HMAC-SHA256-PAYLOAD`, so whenever we try to upload the entire directory, it throws `STREAMING-AWS4-HMAC-SHA256-PAYLOAD not implemented`

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project
- [x] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [x] I have read the **README** document
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

## License

- [x] I confirm that this pull request can be released under the Apache 2 license

[issues]: https://github.com/aws/aws-sdk-net/issues
[license]: http://aws.amazon.com/apache2.0/
[cla]: http://en.wikipedia.org/wiki/Contributor_License_Agreement

### CODE REVIEW

**Review by normj — APPROVED** [review]
The PR looks good.

**Comment by M4urici0GM** [comment]
I've made a change to the variable name, it was causing infinite recursion.
I've tested today and now it's working as intended :D :shipit:

**Review by normj — APPROVED** [review]

**Comment by normj** [comment]
> I've made a change to the variable name, it was causing infinite recursion. I've tested today and now it's working as intended :D :shipit:

Whoops 😄

**Review by boblodgett — APPROVED** [review]

**Comment by M4urici0GM** [comment]
Hi @boblodgett @normj How is the process to get this merged? i'm currently using a .dll file in my repo so i can use this feature xD

**Comment by normj** [comment]
Sorry that is on me to finish up. I'll get that taken care.

**Comment by normj** [comment]
The PR is queued up in our automation system to go out with the next release which will most likely be tomorrow.

**Comment by M4urici0GM** [comment]
Hey men, really appreciate it
🚀

**Pull request merged**
