### PR TITLE
DynamoDB: Generate AttributeValue.IsXXSet properties for SS, BS, and NS

### PR DESCRIPTION
**Pull request by DavidBoike**
## Description

Adds `IsSSSet`, `IsBSSet`, and `IsNSSet` properties to `AttributeValue` to allow empty collections to be stored.

## Motivation and Context

* Fixes https://github.com/aws/aws-sdk-net/issues/3297 - It is not currently possible to store empty string sets, number sets, or binary sets without running into:

> Amazon.DynamoDBv2.AmazonDynamoDBException : Supplied AttributeValue is empty, must contain exactly one of the supported datatypes

## Testing

I'm not sure how to do testing, though I assume the net change of adding to the mapping file as suggested by @normj in https://github.com/aws/aws-sdk-net/issues/3297#issuecomment-2075401652 would only be adding the correlating properties and customization as defined by the generator.

## Screenshots (if appropriate)

N/A

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project
- [x] My change requires a change to the documentation - (Though I assume most of this is generated based on the change)
- [ ] I have updated the documentation accordingly
- [x] I have read the **README** document
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

## License

- [x] I confirm that this pull request can be released under the Apache 2 license

[issues]: https://github.com/aws/aws-sdk-net/issues
[license]: http://aws.amazon.com/apache2.0/
[cla]: http://en.wikipedia.org/wiki/Contributor_License_Agreement

### CODE REVIEW

**Review by normj — APPROVED** [review]
PR looks good. I'll try and get this out soon.

**Comment by danielmarbach** [comment]
@normj after you run the generator will that also generate the implementation similar to https://github.com/aws/aws-sdk-net/blob/main/sdk/src/Services/DynamoDBv2/Generated/Model/AttributeValue.cs#L198-L205 ?

**Comment by normj** [comment]
@danielmarbach Yes. The `IsLSet` that you pointed to was generated in the past because the customization file that @DavidBoike file edited already had the `L` property in the list.

**Comment by danielmarbach** [comment]
@normj myquestion was if the generator will generate a similar access pattern for the new property but I now derive from your answer that it will be the case

**Comment by normj** [comment]
The PR was released as part of version `3.7.302.23` of AWSSDK.DynamoDBv2.

**Comment by danielmarbach** [comment]
Thanks. @normj!

**Pull request merged**
