### PR TITLE
Use [GeneratedRegex] with .NET 8

### LINKED ISSUE #3156: Use Regex source generator when targeting net8.0
### Describe the feature

As part of the .NET 7 release, a [source generator for Regular Expressions was introduced](https://devblogs.microsoft.com/dotnet/regular-expression-improvements-in-dotnet-7/#source-generation).

As the AWS SDKs for .NET now target `net8.0`, this functionality can be leveraged to potentially improve the performance of regular expression operations within the SDKs.

A cursory search of the code suggests there are 20+ places in the code this could potentially be of use: [code search](https://github.com/search?q=repo%3Aaws%2Faws-sdk-net+%22new+Regex%28%22+language%3AC%23&type=code).

A specific example can be found here, which I noticed while looking into #3153:

https://github.com/aws/aws-sdk-net/blob/4650fa53914bdeea1e10fdac42f902638b77eee9/sdk/src/Core/Amazon.Runtime/Credentials/AssumeRoleWithWebIdentityCredentials.cs#L51

This specific example could be changed like this:

```diff
+ #if NET8_0_OR_GREATER
+ [GeneratedRegex(@"^[\w+=,.@-]{2,64}$")]
+ private static partial Regex RoleSessionNameRegex();
+ #else
  private static readonly Regex _roleSessionNameRegex = new Regex(@"^[\w+=,.@-]{2,64}$", RegexOptions.Compiled);
+ private static Regex RoleSessionNameRegex() => _roleSessionNameRegex;
+ #endif
```

The call sites in this case would then be changed from `_roleSessionNameRegex` to `RoleSessionNameRegex()`.

### Use Case

Improve the cold-start and runtime performance of applications using the AWS .NET SDKs.

### Proposed Solution

Update the custom code to use the Regex source generator where the pattern is known at compile-time and update the generated code to do the same.

### Other Information

_No response_

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS .NET SDK and/or Package version used

Anywhere `Regex` is used with a compile-time known pattern.

### Targeted .NET Platform

.NET 8

### Operating System and version

All

### PR DESCRIPTION
**Pull request by martincostello**
## Description

Use `[GeneratedRegex]` for constant patterns when targeting `net8.0`.

Resolves #3156.

## Motivation and Context

Improve performance of the SDK in .NET 8+ applications.

I haven't changed any of the generator code as no `Regex` instances appear to be created for generated code. I also haven't tried to adjust any use of `Regex` in the tests.

## Testing

Locally compiled the build. I haven't _yet_ run the unit tests, but I would expect them to find any issues.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [x] I have read the **README** document
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

## License

- [x] I confirm that this pull request can be released under the Apache 2 license

[issues]: https://github.com/aws/aws-sdk-net/issues
[license]: http://aws.amazon.com/apache2.0/
[cla]: http://en.wikipedia.org/wiki/Contributor_License_Agreement

### CODE REVIEW

**Comment by normj** [comment]
Changes look good. I'm running the branch through our full internal build.

**Comment by normj** [comment]
@martincostello Can you change your branch name from `martincostello:issue-3156-generated-regex` to `martincostello/issue-3156-generated-regex`? Our build system isn't liking the colon in the branch name is getting messed up during merging.

**Comment by martincostello** [comment]
The colon is due to it being a fork, so I can't do anything about that as it's not part of the branch's actual name.

You'd need to either change the repo owner from AWS to my login, or build it from the Git SHA instead of the branch name.

**Comment by normj** [comment]
Running the internal validation took longer then expected because the Regex source generation generated some odd named fields that get written to the ndoc xml file and set off our keyscanner.

```
        <member name="F:System.Text.RegularExpressions.Generated.Utilities.s_ascii_20FF0300000000FEFFFF07">
            <summary>Supports searching for characters in or not in "-0123456789abcdefghijklmnopqrstuvwxyz".</summary>
        </member>
```

I got that taken care of and the full validation build was successful.

**Review by normj — APPROVED** [review]

**Review by dscpinheiro — APPROVED** [review]

**Comment by normj** [comment]
Thanks for the PR @martincostello. The change was released as part of today's release. https://github.com/aws/aws-sdk-net/blob/main/changelogs/SDK.CHANGELOG.2024.md#377380-2024-01-31-1915-utc

**Pull request merged**
