### PR TITLE
Add ToString methods for better enum string conversion

### PR DESCRIPTION
**Pull request by paulomorgado**
## Description

- Added private `ToString` methods for various comparison `enum`s in `ConditionFactory.cs` to improve readability and maintainability.
- Updated `NewCondition` methods to use these new `ToString` methods for consistent string representation.
- Optimized `boolean` conversion to `string` using a ternary operator.

## Motivation and Context

The result of invoking `ToString` on an `enum` is cached in a limited space and there's no guarantee that the value will be cached for the same value in consecutive invocations.

Having code that returns compile-time generated static `string`s will guarantee that that `string` is always available and easy to access.

Invoking `ToString` in `bool` will return the `string`literals `"True"` or `"False"`, depending on its value. However, invoking `ToLowerInvariant()` on those `String`s will incur in the generation/allocation of a new `string` every time.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [X] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have read the **README** document
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

## License

- [ ] I confirm that this pull request can be released under the Apache 2 license

[issues]: https://github.com/aws/aws-sdk-net/issues
[license]: http://aws.amazon.com/apache2.0/
[cla]: http://en.wikipedia.org/wiki/Contributor_License_Agreement

### CODE REVIEW

**Comment by paulomorgado** [comment]
Tests invoking `AssertExtensions.AssertEnumUnchanged` should be added to validate changes to these `enum`s, but I haven't figured out what the best place for it would be.

**Comment by danielmarbach** [comment]
Nice change @paulomorgado

**Comment by paulomorgado** [comment]
> Nice change @paulomorgado

Thanks, @danielmarbach.

Maybe introducing [NetEscapades.EnumGenerators: a source generator for enum performance](https://andrewlock.net/netescapades-enumgenerators-a-source-generator-for-enum-performance/) would be a good option to avoid hand-written code.

**Review by peterrsongg — CHANGES_REQUESTED** [review]
The change itself looks good, but these need unit tests
I think [this](https://github.com/aws/aws-sdk-net/blob/main/sdk/test/UnitTests/Custom/PolicyTests.cs) is a good place to put the tests. 

I think just testing a few is sufficient, probably no reason to test all of them but I would feel more comfortable knowing we had unit tests.

I wrote a method to get the expected hash of the original type

```
    public static class HashingUtils
    {
        private static SHA256 SHA256 = SHA256.Create();
        public static string GetHash(Type type)
        {
            return BitConverter.ToString(SHA256.ComputeHash(Encoding.Default.GetBytes(type.ToString()))).Replace("-","");
        }
    }
```

which you could use to get the expected hash and then pass that in to AssertEnumUnchanged. You may have to tweak it a little

**Comment by paulomorgado** [comment]
> The change itself looks good, but these need unit tests I think [this](https://github.com/aws/aws-sdk-net/blob/main/sdk/test/UnitTests/Custom/PolicyTests.cs) is a good place to put the tests.
> 
> I think just testing a few is sufficient, probably no reason to test all of them but I would feel more comfortable knowing we had unit tests.
> 
> I wrote a method to get the expected hash of the original type
> 
> ```
>     public static class HashingUtils
>     {
>         private static SHA256 SHA256 = SHA256.Create();
>         public static string GetHash(Type type)
>         {
>             return BitConverter.ToString(SHA256.ComputeHash(Encoding.Default.GetBytes(type.ToString()))).Replace("-","");
>         }
>     }
> ```
> 
> which you could use to get the expected hash and then pass that in to AssertEnumUnchanged. You may have to tweak it a little

On it!

**Review by normj — APPROVED** [review]

**Review by peterrsongg — APPROVED** [review]

**Pull request merged**
