### PR TITLE
Handle Cognito Sync Count Exception

### PR DESCRIPTION
**Pull request by pfleeter**
Addresses unhandled mismatch sync count exception per issue #430

### CODE REVIEW

**Comment by aphexyuri** [comment]
@soapyigu can we get this looked at as well?

**Comment by soapyigu** [comment]
In my opinion, this pull request is unnecessary as currently this kind of error falls into data storage exception, which is the base class that data conflict exception extends from.

**Comment by pfleeter** [comment]
@soapyigu Per the issue #430, the problem is that the consumer of this exception is specifically expecting a data conflict exception, not a data storage exception.  See https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/CognitoSync/Custom/SyncManager/Dataset.cs#L619

**Comment by normj** [comment]
Thanks for the pull request. Version 3.3.1.23 of CognitoSync contains this change.

**Pull request merged**
