### PR TITLE
TryParseAmazonS3Uri(string) should not throw

### PR DESCRIPTION
**Pull request by OlegBoulanov**

### CODE REVIEW

**Comment by SrutiG** [comment]
Could you please provide more details in this PR description about your use case and the error message you are getting? We would definitely like to address the issue of a TryParse method throwing an exception.

**Comment by OlegBoulanov** [comment]
https://github.com/OlegBoulanov/aws-sdk-net/commit/e1a59ca501cfce923704b033eb1c619c0ee92666

The problem is that TryParse(string) invokes TryParse(Uri.Parse(string)) internally - which may throw, but TryParse(whatever) should not throw by definition.

**Comment by OlegBoulanov** [comment]
and of course there is a bug... please reject that PR, I will submit another one

**Comment by OlegBoulanov** [comment]
Ok, all set

**Comment by normj** [comment]
This PR was released in the latest version of the SDK

**Pull request merged**
