### PR TITLE
Add possibility to instantiate services with credentials from STS

### LINKED ISSUE #1741: Native support for AssumeRole flow in NetCore.Setup
It would be extremely useful if the AWS SDK supported natively the possibility for assuming a role. 

This is explicitly useful in development phase because it would allow
- IAM/SSO users with very limited permissions (ideally only the possibility to assume roles)
- applications would run also in development with their assigned role thus making it easier to test the role itself before going into production

## Describe the Feature
Starting from this page of the documentation: https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-netcore.html

It would be cool if we could have native support for something like 

```json
// application.Development.json
{
	"AWS": {
		"Region": "eu-north-1",
		"Role": "my-role-to-assume"
	}
}
```

Specifying a role in the configuration should change the workflow for instantiating a service client (e.g. s3) from "fetch credentials from shared file" to
- fetch credentials to shared file
- instantiate sts client with these credentials
- assume specified role
- fetch new credentials
- instantiate service client with new credentials

### Is your Feature Request related to a problem?
In a way it can be done already but I believe it should be part of the SDK and not part of the application code because
- this is purely devops plumbing
- the setup is expected to change between development and production environment and I'd avoid ugly ifs as much as possible
- during development, the applications are running with the users credentials that are usually granted many permissions. This creates friction when moving into production where usually roles are being used.

## Proposed Solution
When a key AWS:Role (or equivalent according to customizability of the setup) is present, the SDK should resolve service client interfaces (e.g. `IAmazonS3`) using the STS client to assume the role and fetch temporary credentials.

Most of the work would be done [here](https://github.com/aws/aws-sdk-net/blob/e9603c9005f6b43054c8bc5e1f826189c99b5395/extensions/src/AWSSDK.Extensions.NETCore.Setup/ClientFactory.cs#L125-L162).

### Describe alternatives you've considered
Polluting the .aws\credentials file with many smaller profiles.

## Additional Context
PROs:
- betters security because IAM users can have less permissions
- better development flow because applications will be developed with their permissions from the beginning

CONs:
- NetCore.Setup would need to take a dependency on the SecurityToken package.

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change  

I might be able to put a simple PR but there are some corner cases that should be investigated properly (e.g. cross account AssumeRole).

---

This is a :rocket: Feature Request

### PR DESCRIPTION
**Pull request by Kralizek**
This is a tentative solution at issue #1741 

## Description
If the user has specified a `SessionRoleArn` in the `AWSOptions`, an instance of `AssumeRoleAWSCredentials` is used to fetch the credentials for the service.

## Motivation and Context
Fixes #1741 

## Testing
This is a tentative solution, I'd welcome feedback from the maintainers before proceeding further with this PR. I created a test console application that link to the project directly.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project
- [x] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [x] I have read the **README** document
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed

## License

- [x] I confirm that this pull request can be released under the Apache 2 license

[issues]: https://github.com/aws/aws-sdk-net/issues
[license]: http://aws.amazon.com/apache2.0/
[cla]: http://en.wikipedia.org/wiki/Contributor_License_Agreement

### CODE REVIEW

**Comment by Kralizek** [comment]
🤔

**Comment by McDoit** [comment]
Any comment/review of this any time soon?

**Comment by Kralizek** [comment]
@McDoit if it can be of any interest for you, I'm thinking about packaging the content of this PR in a standalone NuGet package.

I just have to understand the licensing bits required to package stuff open sourced by aws.

@normj could you give us an insight?

**Review by normj — APPROVED** [review]

**Comment by Kralizek** [comment]
@normj wow, that took a while 😜

**Review by dscpinheiro — APPROVED** [review]

**Comment by normj** [comment]
@Kralizek  Better late then never 😄

**Comment by normj** [comment]
This PR has been merged and released as part of version [3.7.3](https://www.nuget.org/packages/AWSSDK.Extensions.NETCore.Setup/3.7.3)

**Comment by Kralizek** [comment]
I have blogged about how to use this new feature here: https://renatogolia.com/2023/02/15/developing-secure-dotnet-application-using-iam-roles/

**Pull request closed without merging**
