### PR TITLE
Fix performance issue: Check file existence before reading it.

### PR DESCRIPTION
**Pull request by Vfialkin**
## Description

Fix performance issue: Check file existence before reading it. Throwing exceptions is expensive. 

The current approach uses exceptions to control the flow with empty try catches and no logs, which in some cases results in performance downgrade. Added file validation before the file read. It might still happen due to concurrency that file got removed after the validation but it should cover 99% of the normal scenarios.

## Motivation and Context

We found a degradation in performance when a profile file didn't exist. 
## Testing

Manual, unit tests don't need to be updated
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [x] I have read the **README** document
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed

## License

- [x] I confirm that this pull request can be released under the Apache 2 license

[issues]: https://github.com/aws/aws-sdk-net/issues
[license]: http://aws.amazon.com/apache2.0/
[cla]: http://en.wikipedia.org/wiki/Contributor_License_Agreement

### CODE REVIEW

**Comment by Vfialkin** [comment]
Got it,  thanks for the quick review! Committed a fix for null ref.

**Comment by Vfialkin** [comment]
Hi, I just want to confirm if there is anything else I need to do to make it mergeable?

**Comment by Vfialkin** [comment]
Still not merged :)

**Comment by boblodgett** [comment]
Thanks for the PR. We have manually merged the PR and released version 3.3.106.0 of AWSSDK.Core with this change.

**Pull request closed without merging**
