### PR TITLE
Change Unity Engine Path

### PR DESCRIPTION
**Pull request by sunchunqiang**
…Editor\Data\PlaybackEngines\windowsstandalonesupport\Managed\UnityEngine.dll to C:\Program Files\Unity\Editor\Data\Managed\UnityEngine.dll

## Description

Change the path of reference UnityEngine in Unity projects from `C:\Program Files\Unity\Editor\Data\PlaybackEngines\windowsstandalonesupport\Managed\UnityEngine.dll` to `C:\Program Files\Unity\Editor\Data\Managed\UnityEngine.dll`.

## Motivation and Context

With the latest Unity Editor installed, build of Unity projects failed. Checking C:\Program Files\Unity\Editor\Data\PlaybackEngines\windowsstandalonesupport\Managed\UnityEngine .dll  with ildasm, we found that Assembly in the module is empty and  C:\Program Files\Unity\Editor\Data\Managed\UnityEngine.dll contains the correct assembly.

## Testing
 
run command [msbuild build.proj /t:full-build] under buildtools folder, the path of reference UnityEngine in the Unity projects generated should be C:\Program Files\Unity\Editor\Data\Managed\UnityEngine.dll  and all the Unity projects can be built successfully. 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [x] I have read the **README** document
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

## License

- [x] I confirm that this pull request can be released under the Apache 2 license

 
[issues]: https://github.com/aws/aws-sdk-net/issues
[license]: http://aws.amazon.com/apache2.0/
[cla]: http://en.wikipedia.org/wiki/Contributor_License_Agreement

### CODE REVIEW

**Comment by kvasukib** [comment]
@Belorus Thank you for the question! We are testing it on older versions. Will have an update soon.

**Comment by sunchunqiang** [comment]
We tested the change with Unity 2018.1.7, 5.6.6, 5.0.0 and 4.7.0. 
The old path works for Unity 5.6.6, 5.0.0 and 4.7.0.
The new path works  for all of them. 
To test the change with 32 bit Unity 4.7.0, we need change the unitypath in \buildtools\common.targets from "C:\Program Files\Unity" to "C:\Program Files (x86)\Unity"

**Comment by sstevenkang** [comment]
The change looks fine to me.  I am running a test build locally and on the build machine.

**Comment by kvasukib** [comment]
@sstevenkang  Thank you! Let us know any concerns/questions you have.

**Comment by sstevenkang** [comment]
We found this at the last minute that the change is in the generated .cs file, not in the .tt.  Could you update the PR?

**Comment by sunchunqiang** [comment]
I reverted previous change in cs file and added the change to tt file

**Comment by sunchunqiang** [comment]
Hi Kang,

I revert the previous change in cs file and added the change to tt file. Please review the change.


Thanks!
-Sun

**Comment by sstevenkang** [comment]
Thanks! Could you also squash the commits into a single commit?

**Pull request merged**
