### PR TITLE
Extend S3 signed URLs to allow for custom parameters that cannot be altered

### PR DESCRIPTION
**Pull request by mr-olson**
## Description
Added a Parameters property to GetPreSignedURLRequest, so that custom parameters can be included in an S3 request and logged, while assuring they can't be tampered with. See https://docs.aws.amazon.com/AmazonS3/latest/dev/LogFormat.html for logging "x-*" querystring parameters

## Motivation and Context
This allows additional metadata about the request to be logged in S3 request logs, with assurance that it remains unmodified from the value the application set it to. An example might be an application userid, sessionid, or similar identifier for auditing.

## Testing
Generated & retrieved a pre-signed URL both with and without the new property set, generated & retrieved a pre-signed URL with a property set, modified the parameter value and got a failure as expected, generated & retrieved a pre-signed URL with multiple properties set, modified parameter values and got failures as expected.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project
- [x] My change requires a change to the documentation
- [x] I have updated the documentation accordingly
- [x] I have read the **README** document
- [x] I have added tests to cover my changes
- [ ] All new and existing tests passed

## License

- [x] I confirm that this pull request can be released under the Apache 2 license

[issues]: https://github.com/aws/aws-sdk-net/issues
[license]: http://aws.amazon.com/apache2.0/
[cla]: http://en.wikipedia.org/wiki/Contributor_License_Agreement

### CODE REVIEW

**Comment by PavelSafronov** [comment]
Please add the test cases you mentioned to this PR. When running the tests, are you able to see the extra parameters appear in the logs?

**Comment by mr-olson** [comment]
Added and pushed test cases for changing parameter as well as value slightly, and confirmed that tampered querystrings generate errors as expected.

Also confirmed that the bucket access logs contain the fully querystring, including the signed parameters.

**Comment by mr-olson** [comment]
@PavelSafronov wanted to validate the test cases that were added satisfied your comment, so that we can hopefully get this merged.

Thanks!

**Comment by mr-olson** [comment]
@normj I think this is ready to review/merge, but it's not clear what the next steps would be to move this forward. I'm sure the team is busy, but I also don't want this sitting ignored unnecessarily if I've skipped a step in the expected contribution workflow. Thanks!

**Comment by normj** [comment]
Thanks for the pull request. This was released in version 3.3.10.4 of AWSSDK.S3

**Pull request merged**
