### PR TITLE
Perform case-insensitive comparion for action names

### PR DESCRIPTION
**Pull request by hdhilip98**
Fix for #2521

### CODE REVIEW

**Review by normj — APPROVED** [review]

**Comment by normj** [comment]
We should add a unit test for this.

**Comment by hdhilip98** [comment]
Added unit test

**Review by normj — APPROVED** [review]

**Review by 96malhar — APPROVED** [review]

**Comment by normj** [comment]
This PR has been merged and released as part of version [3.7.105](https://www.nuget.org/packages/AWSSDK.Core/3.7.105)

**Comment by hdhilip98** [comment]
@normj The issue persists, and the changes were not found in the `master` branch.

**Pull request closed without merging**
