### PR TITLE
Setting RegionEndpoint only if ServiceURL was not set, because ServiceURL value will be lost otherwise

### PR DESCRIPTION
**Pull request by denisivan0v**
ClientConfig.RegionEndpoint setter resets the ServiceURL property value. So, if ServiceURL was set in AWSOptions.DefaultClientConfig, it's value will be lost. This PR fixes this issue.

### CODE REVIEW

**Comment by normj** [comment]
Thanks for the pull request. Now that .NET Core support has been GA the netcore-development branch is retired and future .NET Core pull request should be done on master. I took care of merging this pull request onto master. We'll get this fix release soon.

**Comment by denisivan0v** [comment]
Sure, I will send next PRs on master if any. Thanks a lot!

**Comment by normj** [comment]
Version 3.3.0.1 of the AWSSDK.Extensions.NETCore.Setup package was pushed to NuGet with this fix. Thanks again for letting us know about the issue.

**Comment by denisivan0v** [comment]
Great! Will test it today.

**Pull request merged**
