### PR TITLE
Update to match new UnityWebRequest API

### PR DESCRIPTION
**Pull request by haswalt**
## Description

Fixes support for Unity 2017.

## Motivation and Context

Allows use with Unity 2017, fixes: #704, #701

## Testing

I'm not a .NET developer and a on MacOS which means testing is awkward. Travis CI builds pass and the change is also very minor and only impacts Unity builds.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [x] I have read the **README** document
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed

## License

- [x] I confirm that this pull request can be released under the Apache 2 license

[issues]: https://github.com/aws/aws-sdk-net/issues
[license]: http://aws.amazon.com/apache2.0/
[cla]: http://en.wikipedia.org/wiki/Contributor_License_Agreement

### CODE REVIEW

**Comment by haswalt** [comment]
Anyway to get these PRs bumped in faster? Currently this prevents the AWS SDK being used with Unity 2017 and there are quite a few bugs about it already that could be closed with this PR.

I can't add more tests or build locally for Unity as I'm on a mac and .Net Core doesn't allow me to build with net35 which Unity needs.

**Comment by oleschaper** [comment]
May I ask what is holding this back?

**Comment by normj** [comment]
I am currently trying to get through our pull requests. Before accepting this I wanted understand first if this would be a breaking change for users not using 2017? Did we have the property wrong before or was it renamed in 2017?

**Comment by oleschaper** [comment]
It was renamed in Unity 2017.1, see
https://docs.unity3d.com/ScriptReference/Networking.UnityWebRequest.html
and
https://docs.unity3d.com/560/Documentation/ScriptReference/Networking.UnityWebRequest.html
So you might be right, for backward compatibility we would need to modify this change.

**Comment by oleschaper** [comment]
tested with Unity 5.6.2, Unity 2017.1.0 and Unity 2017.1.1

**Comment by normj** [comment]
Thanks for the pull request. Version 3.3.17.8 of the Core component contains this fix.

**Comment by barides** [comment]
Hi,

I would like to get Version 3.3.17.8, is there an option to get the distributable for this release or later. In the amazon website the download gives me reels 3.3.12.0 as the latest.

Can any one help out? I need the DLL with this fix.

Thanks

**Pull request merged**
